name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dev-requirements
        run: pip install -r requirements-dev.txt
      - name: Test
        run: python -m pytest
      - name: Install build dependencies
        run: pip install -U setuptools wheel build
      - name: Build
        run: python -m build .
